import { createFlight, stepFlight, WIDTH, HEIGHT } from '/flight-core.mjs';
const $=id=>document.getElementById(id),canvas=$('flight'),ctx=canvas.getContext('2d');
let state=createFlight(),running=false,started=false,last=0,best=0,pointer=null;
try{best=Math.max(0,Number(localStorage.getItem('nike-flight-best'))||0);}catch{}
const keys=new Set(),stars=Array.from({length:95},()=>({x:Math.random()*WIDTH,y:Math.random()*HEIGHT,r:.5+Math.random()*1.4,s:12+Math.random()*38}));
function hud(){$('health').textContent='◆ '.repeat(state.hp)+'◇ '.repeat(3-state.hp);$('score').textContent=Math.floor(state.score);$('level').textContent=String(state.level).padStart(2,'0');$('best').textContent=best;}
function save(){best=Math.max(best,Math.floor(state.score));try{localStorage.setItem('nike-flight-best',String(best));}catch{}hud();}
function start(){if(!started||state.dead){state=createFlight();started=true;}running=true;keys.clear();pointer=null;$('overlay').hidden=true;$('pause').disabled=false;$('restart').disabled=false;$('pause').textContent='暂停';canvas.focus();hud();}
function pause(){if(!running)return;running=false;keys.clear();pointer=null;$('overlay').hidden=false;$('title').textContent='航行已暂停';$('message').textContent='调整一下呼吸，星海会等你。';$('start').textContent='继续飞行 →';$('pause').textContent='继续';save();}
$('start').addEventListener('click',start);$('pause').addEventListener('click',()=>running?pause():start());$('restart').addEventListener('click',()=>{save();started=false;start();});
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLButtonElement)return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d','p',' '].includes(k)){e.preventDefault();if((k==='p'||k===' ')&&!e.repeat){if(started&&!state.dead)running?pause():start();}else keys.add(k);}});
window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
function position(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*WIDTH/r.width,y:(e.clientY-r.top)*HEIGHT/r.height};}
canvas.addEventListener('pointerdown',e=>{if(!running)return;canvas.setPointerCapture(e.pointerId);const p=position(e);pointer={id:e.pointerId,x:p.x,y:p.y,baseX:state.player.x,baseY:state.player.y,targetX:state.player.x,targetY:state.player.y};});
canvas.addEventListener('pointermove',e=>{if(pointer?.id!==e.pointerId)return;const p=position(e);pointer.targetX=pointer.baseX+p.x-pointer.x;pointer.targetY=pointer.baseY+p.y-pointer.y;});
for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,()=>pointer=null);
function draw(now){ctx.fillStyle='#07111f';ctx.fillRect(0,0,WIDTH,HEIGHT);const glow=ctx.createRadialGradient(730,230,20,730,230,480);glow.addColorStop(0,'#11394a');glow.addColorStop(1,'#07111f');ctx.fillStyle=glow;ctx.fillRect(0,0,WIDTH,HEIGHT);
 for(const star of stars){const x=(star.x-state.time*star.s%WIDTH+WIDTH)%WIDTH;ctx.fillStyle='#bfe8ef';ctx.globalAlpha=.25+star.r*.25;ctx.fillRect(x,star.y,star.r*2,star.r);}ctx.globalAlpha=1;
 ctx.strokeStyle='#46757f35';ctx.lineWidth=1;ctx.beginPath();ctx.arc(815,200,115,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.ellipse(815,200,185,40,-.5,0,Math.PI*2);ctx.stroke();
 for(const item of state.items){ctx.save();ctx.translate(item.x,item.y);ctx.rotate(item.angle);if(item.type==='energy'){ctx.shadowBlur=23;ctx.shadowColor='#74f8cd';ctx.fillStyle='#87f9d7';ctx.beginPath();ctx.moveTo(0,-14);ctx.lineTo(11,0);ctx.lineTo(0,14);ctx.lineTo(-11,0);ctx.closePath();ctx.fill();}else{ctx.fillStyle='#44566b';ctx.strokeStyle='#8796a4';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<9;i++){const a=i*Math.PI*2/9,r=item.r*(i%2?.88:1);i?ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r):ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r);}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#2d4055';ctx.beginPath();ctx.arc(-5,-3,item.r*.3,0,Math.PI*2);ctx.fill();}ctx.restore();}
 const p=state.player;ctx.save();ctx.translate(p.x,p.y);ctx.globalAlpha=state.cooldown>0&&Math.floor(now/80)%2?.35:1;ctx.shadowBlur=18;ctx.shadowColor='#57dffb';ctx.fillStyle='#65e4fa';ctx.beginPath();ctx.moveTo(-19,-7);ctx.lineTo(-34-(running?Math.sin(now/45)*8:0),0);ctx.lineTo(-19,7);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#e5f8ff';ctx.beginPath();ctx.moveTo(27,0);ctx.lineTo(-21,-19);ctx.lineTo(-13,0);ctx.lineTo(-21,19);ctx.closePath();ctx.fill();ctx.fillStyle='#4fa7c9';ctx.beginPath();ctx.moveTo(13,0);ctx.lineTo(-10,-7);ctx.lineTo(-10,7);ctx.fill();if(state.cooldown>0){ctx.strokeStyle='#a2f8df';ctx.beginPath();ctx.arc(0,0,32,0,Math.PI*2);ctx.stroke();}ctx.restore();}
function frame(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(running){let input={x:Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),y:Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'))};if(pointer){input={x:(pointer.targetX-state.player.x)/Math.max(1,310*dt),y:(pointer.targetY-state.player.y)/Math.max(1,310*dt)};}stepFlight(state,dt,input);hud();if(state.dead){running=false;keys.clear();pointer=null;save();$('pause').disabled=true;$('overlay').hidden=false;$('title').textContent='这次，飞得很远。';$('message').textContent=`得分 ${Math.floor(state.score)} · 航行 ${Math.floor(state.time)} 秒 · 最佳 ${best}`;$('start').textContent='再飞一次 ↗';}}draw(now);requestAnimationFrame(frame);}
hud();requestAnimationFrame(frame);
