import {boundedSize,checkedSize,cropRect,resizeSize,sniffImage,fitCrop} from './image-edit-core.mjs?v=20260909-3';
import {assertImageDimensions} from './image-input.mjs';
const $=id=>document.getElementById(id), canvas=$('canvas');
let original=null, sourceInfo='', filename='image', revision=0, loadId=0, url='', crop=null, drag=null, loading=false, undoStack=[], redoStack=[], resizeDirty=false, lastResizeAxis="width", fileBytes=0;
const status=(message,error=false)=>{$('status').textContent=message;$('status').classList.toggle('error',error);};
function invalidate(){revision++;if(url)URL.revokeObjectURL(url);url='';$('download').removeAttribute('href');$('result').hidden=true;$('output-preview').removeAttribute('src');$('export').disabled=false;}
function makeCanvas(w,h){checkedSize(w,h);const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
function showCrop(){if(!crop)return;for(const key of ['x','y','width','height'])$('crop-'+key).value=crop[key];const s=$('crop-overlay').style;s.left=100*crop.x/canvas.width+'%';s.top=100*crop.y/canvas.height+'%';s.width=100*crop.width/canvas.width+'%';s.height=100*crop.height/canvas.height+'%';}
function refresh(){resizeDirty=false;$('aspect').value='0';crop={x:0,y:0,width:canvas.width,height:canvas.height};$('width').value=canvas.width;$('height').value=canvas.height;$('dimensions').textContent=`${sourceInfo} · 当前 ${canvas.width} × ${canvas.height} px`;showCrop();}
function replaceCanvas(c,remember=true){if(remember&&original)rememberState();invalidate();canvas.width=c.width;canvas.height=c.height;canvas.getContext('2d').drawImage(c,0,0);refresh();historyControls();}
function run(fn){try{fn();}catch(e){status(e.message,true);}}
function copyCanvas(c){const out=makeCanvas(c.width,c.height);out.getContext('2d').drawImage(c,0,0);return out;}
function historyControls(){$('undo').disabled=loading||!undoStack.length;$('redo').disabled=loading||!redoStack.length;}
function trimHistory(){let bytes=undoStack.reduce((n,c)=>n+c.width*c.height*4,0);while(undoStack.length>1&&(undoStack.length>10||bytes>64*1024*1024)){const old=undoStack.shift();bytes-=old.width*old.height*4;}}
function rememberState(){undoStack.push(copyCanvas(canvas));redoStack=[];trimHistory();}
function historyStep(from,to){if(loading||!from.length)return;to.push(copyCanvas(canvas));replaceCanvas(from.pop(),false);historyControls();status('已恢复上一步画面，导出将使用此版本。');}
$('undo').onclick=()=>historyStep(undoStack,redoStack);
$('redo').onclick=()=>historyStep(redoStack,undoStack);
function readCrop(){const rect=Object.fromEntries(['x','y','width','height'].map(k=>[k,Number($('crop-'+k).value)]));crop=fitCrop(rect,canvas.width,canvas.height,Number($('aspect').value));showCrop();return crop;}
function hasCrop(){return crop&&(crop.x!==0||crop.y!==0||crop.width!==canvas.width||crop.height!==canvas.height);}
function applyCrop(){readCrop();if(!hasCrop())return;const c=makeCanvas(crop.width,crop.height);c.getContext('2d').drawImage(canvas,crop.x,crop.y,crop.width,crop.height,0,0,c.width,c.height);replaceCanvas(c);status('已应用裁剪，画面和导出尺寸已更新。');}
function requestedSize(){return $('lock').checked?resizeSize(canvas.width,canvas.height,Number($(lastResizeAxis).value),lastResizeAxis,true):checkedSize(Number($('width').value),Number($('height').value));}
function applyResize(size=requestedSize()){if(size.width===canvas.width&&size.height===canvas.height){resizeDirty=false;return;}const c=makeCanvas(size.width,size.height),ctx=c.getContext('2d');ctx.imageSmoothingQuality='high';ctx.drawImage(canvas,0,0,c.width,c.height);replaceCanvas(c);status('已应用新尺寸。');}
async function load(file){if(!file)return;if(loading){status('图片正在读取，请稍后再选择。');return;}loading=true;const id=++loadId;invalidate();$('fields').disabled=true;$('reset').disabled=true;status('正在读取图片…');let bitmap;
 try{if(file.size>20*1024*1024)throw new Error('图片超过 20MB，请先选择较小的图片。');const type=sniffImage(new Uint8Array(await file.slice(0,12).arrayBuffer()));if(!type)throw new Error('请选择 PNG、JPEG、WebP 或 BMP 图片。');
 await assertImageDimensions(file);bitmap=await createImageBitmap(new Blob([file],{type}),{imageOrientation:'from-image'});if(id!==loadId)return;
 const {width,height}=boundedSize(bitmap.width,bitmap.height);const c=makeCanvas(width,height);c.getContext('2d').drawImage(bitmap,0,0,width,height);
 undoStack=[];redoStack=[];fileBytes=file.size;original=c;filename=file.name.replace(/\.[^.]+$/,'')||'image';sourceInfo=`原图 ${bitmap.width} × ${bitmap.height} px`;$('filename').textContent=file.name;$('editor').hidden=false;$('drop').hidden=true;$('fields').disabled=false;$('reset').disabled=false;replaceCanvas(c,false);
 status(width!==bitmap.width||height!==bitmap.height?`大图已等比缩小为 ${width} × ${height} px；恢复原图将恢复此工作尺寸。`:'图片已就绪。拖动选择裁剪区域，或直接调整格式导出。');
 }catch(e){if(id===loadId){$('fields').disabled=!original;$('reset').disabled=!original;status(e.message||'无法解码此图片，请换一张重试。',true);}}finally{bitmap?.close();loading=false;historyControls();}}
$('file').addEventListener('change',e=>{load(e.target.files[0]);e.target.value='';});$('replace').onclick=()=>$('file').click();
document.addEventListener('dragover',e=>e.preventDefault());document.addEventListener('drop',e=>{e.preventDefault();load(e.dataTransfer.files[0]);});
$('reset').onclick=()=>{if(!original)return;replaceCanvas(original);status('已恢复最初的工作图。');};
function point(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width,(e.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-r.top)*canvas.height/r.height))};}
canvas.onpointerdown=e=>{if($('fields').disabled||e.button!==0)return;const p=point(e),box=canvas.getBoundingClientRect(),hit=12*canvas.width/box.width;let corner=null;for(const [name,x,y] of [['nw',crop.x,crop.y],['ne',crop.x+crop.width,crop.y],['sw',crop.x,crop.y+crop.height],['se',crop.x+crop.width,crop.y+crop.height]])if(Math.abs(p.x-x)<=hit&&Math.abs(p.y-y)<=hit)corner=name;const inside=crop&&p.x>crop.x&&p.x<crop.x+crop.width&&p.y>crop.y&&p.y<crop.y+crop.height;const full=crop.width===canvas.width&&crop.height===canvas.height;drag={start:p,old:{...crop},corner,move:!corner&&inside&&!full};canvas.setPointerCapture(e.pointerId);};
canvas.onpointermove=e=>{if(!drag)return;const p=point(e),a=drag.start;if(drag.corner){const r=drag.old,anchor={x:drag.corner.includes('w')?r.x+r.width:r.x,y:drag.corner.includes('n')?r.y+r.height:r.y};let w=Math.abs(p.x-anchor.x),h=Math.abs(p.y-anchor.y);const ratio=Number($('aspect').value);if(ratio){w=Math.min(w,h*ratio);h=w/ratio;}crop=fitCrop({x:p.x<anchor.x?anchor.x-w:anchor.x,y:p.y<anchor.y?anchor.y-h:anchor.y,width:Math.max(1,w),height:Math.max(1,h)},canvas.width,canvas.height,ratio);}else if(drag.move){crop={...drag.old,x:Math.round(Math.max(0,Math.min(canvas.width-drag.old.width,drag.old.x+p.x-a.x))),y:Math.round(Math.max(0,Math.min(canvas.height-drag.old.height,drag.old.y+p.y-a.y)))};}else{let w=Math.abs(p.x-a.x),h=Math.abs(p.y-a.y);const ratio=+$('aspect').value;if(ratio){w=Math.min(w,h*ratio);h=w/ratio;}crop=cropRect({x:p.x<a.x?a.x-w:a.x,y:p.y<a.y?a.y-h:a.y,width:Math.max(1,w),height:Math.max(1,h)},canvas.width,canvas.height);}invalidate();showCrop();};
canvas.onpointerup=canvas.onpointercancel=()=>{drag=null;};
for(const key of ['x','y','width','height'])$('crop-'+key).addEventListener('input',()=>{
 invalidate();try{const rect=Object.fromEntries(['x','y','width','height'].map(k=>[k,Number($('crop-'+k).value)]));const ratio=Number($('aspect').value);if(ratio&&key==='height')rect.width=rect.height*ratio;crop=fitCrop(rect,canvas.width,canvas.height,ratio);const style=$('crop-overlay').style;style.left=100*crop.x/canvas.width+'%';style.top=100*crop.y/canvas.height+'%';style.width=100*crop.width/canvas.width+'%';style.height=100*crop.height/canvas.height+'%';if(ratio&&key==='height')$('crop-width').value=crop.width;if(ratio&&key==='width')$('crop-height').value=crop.height;status('选区已预览。点击应用裁剪，或直接导出当前设置。');}catch(e){status(e.message,true);}
});
$('aspect').onchange=()=>{invalidate();const ratio=+$('aspect').value;let w=canvas.width,h=canvas.height;if(ratio){w=Math.min(w,h*ratio);h=w/ratio;}crop=cropRect({x:(canvas.width-w)/2,y:(canvas.height-h)/2,width:w,height:h},canvas.width,canvas.height);showCrop();};
$('apply-crop').onclick=()=>run(applyCrop);
$('clear-crop').onclick=()=>{invalidate();$('aspect').value='0';crop={x:0,y:0,width:canvas.width,height:canvas.height};showCrop();status('已取消裁剪选区。');};
for(const [id,angle] of [['rotate-left',-Math.PI/2],['rotate-right',Math.PI/2]])$(id).onclick=()=>run(()=>{const c=makeCanvas(canvas.height,canvas.width),ctx=c.getContext('2d');ctx.translate(c.width/2,c.height/2);ctx.rotate(angle);ctx.drawImage(canvas,-canvas.width/2,-canvas.height/2);replaceCanvas(c);status('已旋转 90°。');});
for(const axis of ['width','height'])$(axis).oninput=()=>{resizeDirty=true;lastResizeAxis=axis;invalidate();try{if($('lock').checked){const size=requestedSize();$(axis==='width'?'height':'width').value=size[axis==='width'?'height':'width'];}status('尺寸已设置，点击应用尺寸或直接导出。');}catch(e){status(e.message,true);}};
$('lock').onchange=()=>{if($('lock').checked&&resizeDirty)run(()=>{const size=requestedSize();$('width').value=size.width;$('height').value=size.height;});};
$('apply-resize').onclick=()=>run(()=>applyResize());
for(const [id,x,y] of [['flip-horizontal',-1,1],['flip-vertical',1,-1]])$(id).onclick=()=>run(()=>{const c=makeCanvas(canvas.width,canvas.height),ctx=c.getContext('2d');ctx.translate(x<0?c.width:0,y<0?c.height:0);ctx.scale(x,y);ctx.drawImage(canvas,0,0);replaceCanvas(c);status('已翻转图片。');});
function formatChanged(){invalidate();const type=$('format').value;$('quality-control').hidden=type==='image/png';$('background-control').hidden=type!=='image/jpeg';$('quality-value').value=$('quality').value+'%';$('format-note').textContent=type==='image/png'?'PNG 无损编码，不保证文件变小。缩小尺寸可进一步减小体积。':type==='image/jpeg'?'降低画质可减小体积；透明区域将填充所选底色。':'降低画质可减小体积，透明区域保留。实际大小以导出结果为准。';}
for(const id of ['format','quality','background'])$(id).addEventListener('input',formatChanged);
$('export').onclick=async()=>{try{readCrop();const pending=resizeDirty?{width:Number($('width').value),height:Number($('height').value),axis:lastResizeAxis,locked:$('lock').checked}:null;applyCrop();if(pending){const size=pending.locked?resizeSize(canvas.width,canvas.height,pending[pending.axis],pending.axis,true):checkedSize(pending.width,pending.height);applyResize(size);}}catch(e){status(e.message,true);return;}const version=revision;const type=$('format').value;$('export').disabled=true;status('正在生成导出预览…');try{const c=makeCanvas(canvas.width,canvas.height),ctx=c.getContext('2d');if(type==='image/jpeg'){ctx.fillStyle=$('background').value;ctx.fillRect(0,0,c.width,c.height);}ctx.drawImage(canvas,0,0);const blob=await new Promise(resolve=>c.toBlob(resolve,type,+$('quality').value/100));if(version!==revision)return;if(!blob)throw new Error('导出失败，请缩小尺寸重试。');if(blob.type!==type)throw new Error('浏览器不支持此导出格式，请选择 PNG 或 JPEG。');if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(blob);$('output-preview').src=url;$('download').href=url;$('download').download=filename+'-edited.'+({'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[blob.type]);$('output-size').textContent=`${c.width} × ${c.height} · ${(blob.size/1024).toFixed(1)} KB · 原文件 ${(fileBytes/1024).toFixed(1)} KB${fileBytes?` · ${blob.size<fileBytes?'减小':'增加'} ${Math.abs((1-blob.size/fileBytes)*100).toFixed(1)}%`:''}`;$('result').hidden=false;status('导出已生成，预览与下载为同一文件。');}catch(e){if(version===revision)status(e.message,true);}finally{if(version===revision)$('export').disabled=false;}};
window.addEventListener('pagehide',()=>{if(url)URL.revokeObjectURL(url);});
