import {createGame,step} from '/never-retreat-core.mjs';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');let g=createGame(),running=false,started=false,last=0,keys=new Set(),stick={x:0,y:0},best=0;
try{best=Number(localStorage.getItem('never-retreat-best'))||0;}catch{}$('best').textContent=best;
function hud(){$('health').textContent=g.player.hp;$('wave').textContent=String(g.wave).padStart(2,'0');$('score').textContent=g.score;}
function show(title,message,label){$('overlay').hidden=false;$('title').textContent=title;$('message').textContent=message;$('start').textContent=label;}
function pause(){if(!running)return;running=false;pointer=null;keys.clear();stick={x:0,y:0};$('touchpad').firstElementChild.style.transform='';show('暂停一下','阵地还在，准备好了就继续。','继续战斗 →');$('pause').disabled=true;}
$('start').onclick=()=>{if(!started||g.over){g=createGame();started=true;}running=true;keys.clear();$('overlay').hidden=true;$('pause').disabled=false;last=performance.now();canvas.focus();hud();};$('pause').onclick=pause;
window.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT|BUTTON|A/.test(e.target.tagName))return;if(e.repeat&&e.key.toLowerCase()==='p')return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key)&&started)e.preventDefault();if(e.key.toLowerCase()==='p'){if(running)pause();else if(started&&!g.over)$('start').click();return;}if(running)keys.add(e.key.toLowerCase());});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
let pointer=null;const pad=$('touchpad');function move(e){if(pointer!==e.pointerId)return;const r=pad.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/36,y=(e.clientY-r.top-r.height/2)/36,len=Math.max(1,Math.hypot(x,y));stick={x:x/len,y:y/len};pad.firstElementChild.style.transform=`translate(${stick.x*30}px,${stick.y*30}px)`;}
pad.onpointerdown=e=>{if(!running||pointer!==null)return;pointer=e.pointerId;pad.setPointerCapture(pointer);move(e);};pad.onpointermove=move;pad.onpointerup=pad.onpointercancel=e=>{if(pointer!==e.pointerId)return;pointer=null;stick={x:0,y:0};pad.firstElementChild.style.transform='';};
function paint(){const w=960,h=600;ctx.fillStyle='#0b1121';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#172338';ctx.lineWidth=1;for(let x=0;x<w;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.strokeStyle='#365673';ctx.strokeRect(16,16,928,568);
 for(const b of g.bullets){ctx.fillStyle='#fce4a4';ctx.beginPath();ctx.arc(b.x,b.y,3,0,Math.PI*2);ctx.fill();}
 for(const e of g.enemies){ctx.save();ctx.translate(e.x,e.y);ctx.rotate(Math.atan2(g.player.y-e.y,g.player.x-e.x));ctx.fillStyle=e.hp>1?'#fda86e':'#f36887';ctx.beginPath();ctx.moveTo(e.r,0);ctx.lineTo(-e.r,-e.r*.7);ctx.lineTo(-e.r*.5,0);ctx.lineTo(-e.r,e.r*.7);ctx.closePath();ctx.fill();ctx.restore();}
 const p=g.player;ctx.save();ctx.translate(p.x,p.y);ctx.strokeStyle='#59e6bf33';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,29,0,Math.PI*2);ctx.stroke();ctx.fillStyle=g.hurt>0?'#fff':'#59e6bf';ctx.beginPath();ctx.arc(0,0,13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#173749';ctx.fillRect(-5,-5,10,10);ctx.restore();}
function frame(now){const dt=(now-last)/1000;last=now;if(running){step(g,dt,{x:(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+stick.x,y:(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+stick.y});hud();if(g.over){running=false;$('pause').disabled=true;if(g.score>best){best=g.score;try{localStorage.setItem('never-retreat-best',String(best));}catch{}$('best').textContent=best;}show('下一次，守得更久',`坚持 ${Math.floor(g.time)} 秒 · 击败 ${g.kills} 名敌人 · 得分 ${g.score}`,'重新挑战 →');}}paint();requestAnimationFrame(frame);}requestAnimationFrame(frame);
